In [2]:
import numpy as np

In [ ]:
# 查看 numpy 版本
np.__version__

'2.1.2'

In [13]:
np.random.random((2, 3))

array([[0.15829587, 0.95648965, 0.09788744],
       [0.13440707, 0.34285846, 0.31140386]])

In [15]:
np.random.randn(3)

array([ 0.13083734, -0.86120244, -1.27071877])

In [17]:
np.random.uniform(1, 2, (2, 3))

array([[1.98471926, 1.14734148, 1.59886871],
       [1.98037934, 1.76787995, 1.56733011]])

In [53]:
np.random.randint(2, 10, (2, 3))

array([[2, 7, 6],
       [2, 8, 3]])

In [54]:
np.random.normal(0, 1, (2, 3))

array([[-0.37069582,  1.41071895, -0.44526405],
       [ 1.45266887, -0.16308713,  1.86545475]])

In [70]:
ls = np.linspace(0, 10, 9, endpoint=False)
np.random.shuffle(ls)
ls

array([2.22222222, 1.11111111, 5.55555556, 3.33333333, 8.88888889,
       7.77777778, 4.44444444, 0.        , 6.66666667])

In [ ]:
# np,random.seed(0)

In [82]:
np.random.sample((2, 3))

array([[0.31210889, 0.31643688, 0.78973821],
       [0.26805154, 0.21158116, 0.01055491]])

In [83]:
np.full((2, 3), 7)

array([[7, 7, 7],
       [7, 7, 7]])

In [95]:
arr = np.empty((2, 3))
arr

array([[0.31210889, 0.31643688, 0.78973821],
       [0.26805154, 0.21158116, 0.01055491]])

In [96]:
np.savetxt(r'./arr.txt', arr)
np.loadtxt(r'./arr.txt')


array([[0.31210889, 0.31643688, 0.78973821],
       [0.26805154, 0.21158116, 0.01055491]])

In [98]:
arr = np.random.normal(0, 1, (4, 4))
arr

array([[-0.2946857 ,  0.23273033,  0.71291191, -0.38211035],
       [ 0.18354318,  0.82694047,  1.43101114, -2.01836289],
       [-0.70703291,  0.12522285, -0.0056278 , -1.17837462],
       [ 0.35513297, -0.95000751, -0.79158512,  0.17247285]])

In [99]:
arr[0]

array([-0.2946857 ,  0.23273033,  0.71291191, -0.38211035])

In [100]:
# np.multiply()
# np.dot()

In [101]:
arr

array([[-0.2946857 ,  0.23273033,  0.71291191, -0.38211035],
       [ 0.18354318,  0.82694047,  1.43101114, -2.01836289],
       [-0.70703291,  0.12522285, -0.0056278 , -1.17837462],
       [ 0.35513297, -0.95000751, -0.79158512,  0.17247285]])

### NumPy 数组变换方法对比表

| 方法名        | 是否修改原数组 | 返回对象类型    | 是否共享内存 | 说明 |
|---------------|----------------|------------------|----------------|------|
| `reshape()`   | 否             | 视图 / 副本      | 是（通常共享） | 内存连续时返回视图，否则返回副本 |
| `resize()`    | 是             | 无（原地修改）   | 无             | 原地修改 shape，可能填充或截断 |
| `ravel()`     | 否             | 视图 / 副本      | 是（通常共享） | 优先返回视图，内存不连续时为副本 |
| `flatten()`   | 否             | 副本             | 否             | 始终返回复制的新数组 |
| `view()`      | 否             | 视图 / 副本      | 是（通常共享） | dtype 改变通常共享内存，存储不连续可能复制 |
| `squeeze()`   | 否             | 视图             | 是             | 删除 shape 中为 1 的维度，不复制内存 |

In [103]:
arr1 = arr.reshape((2, 8))
arr1

array([[-0.2946857 ,  0.23273033,  0.71291191, -0.38211035,  0.18354318,
         0.82694047,  1.43101114, -2.01836289],
       [-0.70703291,  0.12522285, -0.0056278 , -1.17837462,  0.35513297,
        -0.95000751, -0.79158512,  0.17247285]])

In [105]:
arr1[0, 0] = 666
arr1

array([[ 6.66000000e+02,  2.32730333e-01,  7.12911913e-01,
        -3.82110345e-01,  1.83543178e-01,  8.26940465e-01,
         1.43101114e+00, -2.01836289e+00],
       [-7.07032910e-01,  1.25222851e-01, -5.62780223e-03,
        -1.17837462e+00,  3.55132970e-01, -9.50007512e-01,
        -7.91585123e-01,  1.72472854e-01]])

In [106]:
arr

array([[ 6.66000000e+02,  2.32730333e-01,  7.12911913e-01,
        -3.82110345e-01],
       [ 1.83543178e-01,  8.26940465e-01,  1.43101114e+00,
        -2.01836289e+00],
       [-7.07032910e-01,  1.25222851e-01, -5.62780223e-03,
        -1.17837462e+00],
       [ 3.55132970e-01, -9.50007512e-01, -7.91585123e-01,
         1.72472854e-01]])

In [109]:
arr.resize((4, 4))
arr

array([[ 6.66000000e+02,  2.32730333e-01,  7.12911913e-01,
        -3.82110345e-01],
       [ 1.83543178e-01,  8.26940465e-01,  1.43101114e+00,
        -2.01836289e+00],
       [-7.07032910e-01,  1.25222851e-01, -5.62780223e-03,
        -1.17837462e+00],
       [ 3.55132970e-01, -9.50007512e-01, -7.91585123e-01,
         1.72472854e-01]])

In [112]:
arr2 = arr.ravel()
arr2

array([ 6.66000000e+02,  2.32730333e-01,  7.12911913e-01, -3.82110345e-01,
        1.83543178e-01,  8.26940465e-01,  1.43101114e+00, -2.01836289e+00,
       -7.07032910e-01,  1.25222851e-01, -5.62780223e-03, -1.17837462e+00,
        3.55132970e-01, -9.50007512e-01, -7.91585123e-01,  1.72472854e-01])

In [114]:
arr2[0] = 0
arr2

array([ 0.        ,  0.23273033,  0.71291191, -0.38211035,  0.18354318,
        0.82694047,  1.43101114, -2.01836289, -0.70703291,  0.12522285,
       -0.0056278 , -1.17837462,  0.35513297, -0.95000751, -0.79158512,
        0.17247285])

In [115]:
arr

array([[ 0.        ,  0.23273033,  0.71291191, -0.38211035],
       [ 0.18354318,  0.82694047,  1.43101114, -2.01836289],
       [-0.70703291,  0.12522285, -0.0056278 , -1.17837462],
       [ 0.35513297, -0.95000751, -0.79158512,  0.17247285]])

In [117]:
arr3 = arr.flatten()
arr3

array([ 0.        ,  0.23273033,  0.71291191, -0.38211035,  0.18354318,
        0.82694047,  1.43101114, -2.01836289, -0.70703291,  0.12522285,
       -0.0056278 , -1.17837462,  0.35513297, -0.95000751, -0.79158512,
        0.17247285])

In [118]:
arr3[0] = 666
arr3

array([ 6.66000000e+02,  2.32730333e-01,  7.12911913e-01, -3.82110345e-01,
        1.83543178e-01,  8.26940465e-01,  1.43101114e+00, -2.01836289e+00,
       -7.07032910e-01,  1.25222851e-01, -5.62780223e-03, -1.17837462e+00,
        3.55132970e-01, -9.50007512e-01, -7.91585123e-01,  1.72472854e-01])

In [119]:
arr

array([[ 0.        ,  0.23273033,  0.71291191, -0.38211035],
       [ 0.18354318,  0.82694047,  1.43101114, -2.01836289],
       [-0.70703291,  0.12522285, -0.0056278 , -1.17837462],
       [ 0.35513297, -0.95000751, -0.79158512,  0.17247285]])

In [123]:
arr = np.random.normal(0, 1, (1, 2, 3, 4))
arr

array([[[[-0.48244776,  0.56522688,  0.86384689, -1.79265885],
         [-0.30037567,  1.68221478, -1.03425226,  0.50836513],
         [-0.30657287,  1.36081112,  1.27714209,  0.62477869]],

        [[ 0.16039185, -0.12065055,  0.91102377,  0.24654577],
         [ 0.22583173, -0.24375181, -0.83935286,  0.90177844],
         [ 0.65718154,  1.32161922,  0.60604675, -2.30795525]]]])

In [127]:
arr4 = arr.squeeze()
arr4

array([[[-0.48244776,  0.56522688,  0.86384689, -1.79265885],
        [-0.30037567,  1.68221478, -1.03425226,  0.50836513],
        [-0.30657287,  1.36081112,  1.27714209,  0.62477869]],

       [[ 0.16039185, -0.12065055,  0.91102377,  0.24654577],
        [ 0.22583173, -0.24375181, -0.83935286,  0.90177844],
        [ 0.65718154,  1.32161922,  0.60604675, -2.30795525]]])

In [128]:
arr4[0, 0, 0] = 0
arr4

array([[[ 0.        ,  0.56522688,  0.86384689, -1.79265885],
        [-0.30037567,  1.68221478, -1.03425226,  0.50836513],
        [-0.30657287,  1.36081112,  1.27714209,  0.62477869]],

       [[ 0.16039185, -0.12065055,  0.91102377,  0.24654577],
        [ 0.22583173, -0.24375181, -0.83935286,  0.90177844],
        [ 0.65718154,  1.32161922,  0.60604675, -2.30795525]]])

In [129]:
arr

array([[[[ 0.        ,  0.56522688,  0.86384689, -1.79265885],
         [-0.30037567,  1.68221478, -1.03425226,  0.50836513],
         [-0.30657287,  1.36081112,  1.27714209,  0.62477869]],

        [[ 0.16039185, -0.12065055,  0.91102377,  0.24654577],
         [ 0.22583173, -0.24375181, -0.83935286,  0.90177844],
         [ 0.65718154,  1.32161922,  0.60604675, -2.30795525]]]])

In [154]:
# 生成一个 3 行 4 列的二维正态分布数组
arr1 = np.random.normal(0, 1, (3, 4))
print("arr1:\n", arr1)

# 生成一个 3 行 1 列的二维数组，便于列方向拼接
arr2 = np.random.normal(0, 1, (3, 1))
print("arr2:\n", arr2)

# 生成一个形状为 (3,) 的一维数组，注意：它不是二维！
arr3 = np.random.normal(0, 1, (3,))
print("arr3:\n", arr3)

# 尝试将 arr2 以列的方式（axis=1）拼接到 arr1
try:
    # arr2 是形状 (3, 1)，与 arr1 的行数匹配，因此可以在 axis=1 方向拼接成功
    result1 = np.append(arr1, arr2, axis=1)
    print("arr1 append arr2 (axis=1):\n", result1)
except Exception as e:
    # 如果形状不匹配，这里会报错
    print("Error appending arr2:", e)

# 尝试将一维数组 arr3 以列的方式拼接到二维数组 arr1
try:
    # arr3 是一维的，形状为 (3,)，不能与二维的 arr1 沿 axis=1 直接拼接，会报错
    result2 = np.append(arr1, arr3, axis=1)
    print("arr1 append arr3 (axis=1):\n", result2)
except Exception as e:
    print("Error appending arr3:", e)

arr1:
 [[-0.6938329   1.13702887 -0.51227789 -0.29250922]
 [ 0.53400645  0.00572883 -1.19870032  0.33189743]
 [-1.48369378  1.42542308  0.36741714  0.04006252]]
arr2:
 [[ 0.90036064]
 [-0.26514976]
 [-0.0203457 ]]
arr3:
 [ 2.44078981 -1.81026863 -1.43550648]
arr1 append arr2 (axis=1):
 [[-0.6938329   1.13702887 -0.51227789 -0.29250922  0.90036064]
 [ 0.53400645  0.00572883 -1.19870032  0.33189743 -0.26514976]
 [-1.48369378  1.42542308  0.36741714  0.04006252 -0.0203457 ]]
Error appending arr3: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


In [155]:
# 生成一个 3x4 的二维数组
arr1 = np.random.normal(0, 1, (3, 4))
print("arr1:\n", arr1)

# 生成一个 3x1 的二维数组
arr2 = np.random.normal(0, 1, (3, 1))
print("arr2:\n", arr2)

# 生成一个形状为 (3,) 的一维数组
arr3 = np.random.normal(0, 1, (3,))
print("arr3:\n", arr3)

# 使用 concatenate 拼接 arr1 和 arr2（两个都是二维，且在 axis=1 上维度对齐）
try:
    result1 = np.concatenate([arr1, arr2], axis=1)
    print("arr1 concatenate arr2 (axis=1):\n", result1)
except Exception as e:
    print("Error concatenating arr2:", e)

# 直接拼接 arr3 会报错，因为它是一维数组，无法与二维数组在 axis=1 拼接
try:
    result2 = np.concatenate([arr1, arr3], axis=1)
    print("arr1 concatenate arr3 (axis=1):\n", result2)
except Exception as e:
    print("Error concatenating arr3:", e)

arr1:
 [[ 0.9571844   1.67950209 -0.53400639 -1.08540915]
 [-0.61603417 -1.29591112  0.11872013 -0.7609852 ]
 [ 0.99547945  0.57250727 -0.87033468 -0.86973735]]
arr2:
 [[ 0.0565884 ]
 [-0.24255351]
 [-1.22321533]]
arr3:
 [ 1.74102559  0.20300003 -1.81903891]
arr1 concatenate arr2 (axis=1):
 [[ 0.9571844   1.67950209 -0.53400639 -1.08540915  0.0565884 ]
 [-0.61603417 -1.29591112  0.11872013 -0.7609852  -0.24255351]
 [ 0.99547945  0.57250727 -0.87033468 -0.86973735 -1.22321533]]
Error concatenating arr3: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


In [157]:
arr1, arr2

(array([[ 0.9571844 ,  1.67950209, -0.53400639, -1.08540915],
        [-0.61603417, -1.29591112,  0.11872013, -0.7609852 ],
        [ 0.99547945,  0.57250727, -0.87033468, -0.86973735]]),
 array([[ 0.0565884 ],
        [-0.24255351],
        [-1.22321533]]))

In [163]:
# 创建一个 3 行 4 列的数组
arr1 = np.random.normal(0, 1, (3, 4))
print("arr1:\n", arr1)

# 使用 np.stack 在新轴上堆叠两个 arr1
stacked = np.stack([arr1, arr1], axis=2)
print("np.stack([arr1, arr1]):\n", stacked)
print("stacked.shape:", stacked.shape)

arr1:
 [[ 0.40058509  0.13635073 -1.07130739  0.81579062]
 [-0.38695982 -0.83141009  2.47806454  2.59944576]
 [-0.04580125 -2.50626285  0.19539998  1.83521169]]
np.stack([arr1, arr1]):
 [[[ 0.40058509  0.40058509]
  [ 0.13635073  0.13635073]
  [-1.07130739 -1.07130739]
  [ 0.81579062  0.81579062]]

 [[-0.38695982 -0.38695982]
  [-0.83141009 -0.83141009]
  [ 2.47806454  2.47806454]
  [ 2.59944576  2.59944576]]

 [[-0.04580125 -0.04580125]
  [-2.50626285 -2.50626285]
  [ 0.19539998  0.19539998]
  [ 1.83521169  1.83521169]]]
stacked.shape: (3, 4, 2)


In [165]:
# 创建两个形状相同的二维数组 (3, 4)
arr1 = np.random.randint(0, 10, (3, 4))
arr2 = np.random.randint(0, 10, (3, 4))

print("arr1:\n", arr1)
print("arr2:\n", arr2)# 横向拼接（按列拼接），结果 shape = (3, 8)
h = np.hstack([arr1, arr2])
print("np.hstack:\n", h)
print("shape:", h.shape)

arr1:
 [[7 3 6 0]
 [3 5 4 6]
 [3 1 3 2]]
arr2:
 [[5 2 2 1]
 [5 0 8 8]
 [7 2 1 7]]
np.hstack:
 [[7 3 6 0 5 2 2 1]
 [3 5 4 6 5 0 8 8]
 [3 1 3 2 7 2 1 7]]
shape: (3, 8)


In [166]:
# 纵向拼接（按行拼接），结果 shape = (6, 4)
v = np.vstack([arr1, arr2])
print("np.vstack:\n", v)
print("shape:", v.shape)

np.vstack:
 [[7 3 6 0]
 [3 5 4 6]
 [3 1 3 2]
 [5 2 2 1]
 [5 0 8 8]
 [7 2 1 7]]
shape: (6, 4)


In [167]:
# 深度方向堆叠，增加一个第三维，结果 shape = (3, 4, 2)
d = np.dstack([arr1, arr2])
print("np.dstack:\n", d)
print("shape:", d.shape)

np.dstack:
 [[[7 5]
  [3 2]
  [6 2]
  [0 1]]

 [[3 5]
  [5 0]
  [4 8]
  [6 8]]

 [[3 7]
  [1 2]
  [3 1]
  [2 7]]]
shape: (3, 4, 2)
